queue_rules:
  - name: Sensitive files
    queue_conditions:
      - files~=^noggin/security/
      - label!=WIP
      - -draft
      - approved-reviews-by=@fedora-infra/authdev
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - status-success=DCO
      - status-success=Misc tests (lint)
      - status-success=Misc tests (format)
      - status-success=Misc tests (security)
      - status-success=Misc tests (docs)
      - status-success=Unit tests (py39-unittest)
      - status-success=Unit tests (py310-unittest)
      - status-success=Integration tests (3.9)
      - status-success=Integration tests (3.10)
    merge_method: rebase
  - name: default
    queue_conditions:
      - -files~=^noggin/security/
      - label!=WIP
      - -draft
      - approved-reviews-by=@fedora-infra/authdev
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=DCO
      - status-success=Misc tests (lint)
      - status-success=Misc tests (format)
      - status-success=Misc tests (security)
      - status-success=Misc tests (docs)
      - status-success=Unit tests (py39-unittest)
      - status-success=Unit tests (py310-unittest)
      - status-success=Integration tests (3.9)
      - status-success=Integration tests (3.10)
    merge_method: rebase

pull_request_rules:
  - name: Automatic merge on approval + Sensitive files
    conditions: []
    actions:
      queue:
